-   id: private_key_check
    name: detect private keys
    description: Check for any private keys in staged files
    entry: private_key_check
    language: python
    types: [text]
    stages: [commit]
    files: .
