-   id: private_key_check
    name: detect private keys
    description: Check for any private keys in staged files
    entry: python pre_commit_hooks/private_key_check.py
    language: python
    types: [text]
    stages: [commit]
