-   id: private_key_check
    name: detect private keys
    description: Check for any private keys in staged files
    entry: private_key_check
    language: python
    types: [text]
    stages: [commit]
    files: .

-   id: docker-compose-validate
    name: Docker Compose Config Validation
    entry: ./validate_docker_compose.sh
    language: system
    pass_filenames: false
    verbose: true
    stages: [pre-commit]

-   id: hadolint-dockerfile-lint
    name: Hadolint Dockerfile Lint
    entry: ./run_hadolint.sh
    language: system
    pass_filenames: false
    verbose: true
    stages: [pre-commit]

-   id: json-lint
    name: JSON Lint
    entry: ./run_json_linter.sh
    language: system
    pass_filenames: false
    verbose: true
    stages: [pre-commit]

-   id: yamllint
    name: Yaml Lint
    entry: ./run_yamllint.sh
    language: system
    pass_filenames: false
    stages: [pre-commit]